/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo2;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Happy
 */
public class details_esti_cust extends javax.swing.JFrame {
/**
     * Creates new form details_esti_cust
     */
    public details_esti_cust() 
    {
        
        initComponents();
        try {
                    Class.forName("com.mysql.jdbc.Driver");
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/list_info?zeroDateTimeBehavior=convertToNull","root","");     
                    st = conn.createStatement();
                    JOptionPane.showMessageDialog(null,"Connected");
    // MySQL database connection
                } 
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Not Connected");
                } 
               
    }
    public details_esti_cust(String as,String s)
    {
        this.setUndecorated(true);
        this.setVisible(true);
        
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        
            int xsize = (int)tk.getScreenSize().getWidth();
            int ysize = (int)tk.getScreenSize().getHeight();
            this.setSize(xsize,ysize);
        
        try{
                    Class.forName("com.mysql.jdbc.Driver");
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/list_info?zeroDateTimeBehavior=convertToNull","root","");     
                    st = conn.createStatement();
                    JOptionPane.showMessageDialog(null,"Connected");
    // MySQL database connection
                } 
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Not Connected");
                } 
             //  String ass=""+as;
       // JOptionPane.showMessageDialog(null,as);

        jLabel2.setText(s);

        jcust_Idtextfield2.setText(as);
                currentDate1();
                        //JOptionPane.showMessageDialog(null,"+++");

             

    }

    public void currentDate1()
    {
            Calendar cal=new GregorianCalendar();
             int day=cal.get( Calendar.DAY_OF_MONTH);
             int month=cal.get( Calendar.MONTH);
             int year=cal.get( Calendar.YEAR);
             joutTextField.setText(day+"/"+(month+1)+"/"+year);

            
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jdeviceLabel8 = new javax.swing.JLabel();
        jbalancetextfield1 = new javax.swing.JTextField();
        jdeviceLabel9 = new javax.swing.JLabel();
        jcust_Idtextfield2 = new javax.swing.JTextField();
        jdeviceLabel10 = new javax.swing.JLabel();
        jreceivedtextfield3 = new javax.swing.JTextField();
        jdeviceLabel11 = new javax.swing.JLabel();
        jremarktextfield4 = new javax.swing.JTextField();
        jsubmitButton1 = new javax.swing.JButton();
        jdeviceLabel12 = new javax.swing.JLabel();
        jestimatetextfield3 = new javax.swing.JTextField();
        joutTextField = new javax.swing.JFormattedTextField();
        joutLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(79, 195, 247));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText(" ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText(" Cutomer_Information");

        jdeviceLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jdeviceLabel8.setText(" Cust_Id:");

        jbalancetextfield1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbalancetextfield1.setText(" ");
        jbalancetextfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jbalancetextfield1FocusGained(evt);
            }
        });
        jbalancetextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbalancetextfield1ActionPerformed(evt);
            }
        });
        jbalancetextfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jbalancetextfield1KeyTyped(evt);
            }
        });

        jdeviceLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jdeviceLabel9.setText("  Balance :");

        jcust_Idtextfield2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcust_Idtextfield2.setText(" ");
        jcust_Idtextfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcust_Idtextfield2ActionPerformed(evt);
            }
        });
        jcust_Idtextfield2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcust_Idtextfield2KeyTyped(evt);
            }
        });

        jdeviceLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jdeviceLabel10.setText("  Received:");

        jreceivedtextfield3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jreceivedtextfield3.setText(" ");
        jreceivedtextfield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jreceivedtextfield3FocusLost(evt);
            }
        });
        jreceivedtextfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreceivedtextfield3ActionPerformed(evt);
            }
        });
        jreceivedtextfield3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jreceivedtextfield3KeyTyped(evt);
            }
        });

        jdeviceLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jdeviceLabel11.setText("  Remark:");

        jremarktextfield4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jremarktextfield4.setText(" ");
        jremarktextfield4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremarktextfield4ActionPerformed(evt);
            }
        });
        jremarktextfield4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jremarktextfield4KeyTyped(evt);
            }
        });

        jsubmitButton1.setBackground(new java.awt.Color(204, 204, 255));
        jsubmitButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jsubmitButton1.setText(" Submit");
        jsubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitButton1ActionPerformed(evt);
            }
        });
        jsubmitButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsubmitButton1KeyPressed(evt);
            }
        });

        jdeviceLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jdeviceLabel12.setText("  Estimate:");

        jestimatetextfield3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jestimatetextfield3.setText(" ");
        jestimatetextfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jestimatetextfield3ActionPerformed(evt);
            }
        });
        jestimatetextfield3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jestimatetextfield3KeyTyped(evt);
            }
        });

        joutTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        joutTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        joutTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        joutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joutTextFieldActionPerformed(evt);
            }
        });

        joutLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        joutLabel6.setText(" Out_Date:");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText(" Cancel");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        print.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        print.setText(" Preview");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdeviceLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(joutLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdeviceLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdeviceLabel9)
                        .addComponent(jdeviceLabel10)
                        .addComponent(jdeviceLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbalancetextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jremarktextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreceivedtextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jestimatetextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcust_Idtextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jsubmitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdeviceLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcust_Idtextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joutLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jestimatetextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdeviceLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jreceivedtextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdeviceLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbalancetextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdeviceLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jremarktextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdeviceLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsubmitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joutTextFieldActionPerformed

    private void jestimatetextfield3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jestimatetextfield3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jestimatetextfield3KeyTyped

    private void jestimatetextfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jestimatetextfield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jestimatetextfield3ActionPerformed

    private void jsubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitButton1ActionPerformed

        String id=jcust_Idtextfield2.getText().trim();
        String out= joutTextField.getText();
        String estimate=jestimatetextfield3.getText();
        String received=jreceivedtextfield3.getText();
        String balance=jbalancetextfield1.getText();
        String remark =jremarktextfield4.getText();
       // JOptionPane.showMessageDialog(null,"+++"+id);
        int cust_ID=0;
        try{
            
        
        cust_ID=Integer.parseInt(id);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Exception XXXXXX");}
       String sql1="update customer SET Out_Date='"+out+"',Estimate='"+estimate+"',Received='"+received+"',Balance='"+balance+"',Remark='"+remark+"' where cust_Id="+cust_ID+"";

        JOptionPane.showMessageDialog(null,sql1);
        try {
          

            //ResultSet rs;
            st.executeUpdate(sql1);
            
            JOptionPane.showMessageDialog(null,"payment completed");

        } catch (Exception e) {
                      //JOptionPane.showMessageDialog(null,"#############");

            JOptionPane.showMessageDialog(null,e);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jsubmitButton1ActionPerformed

    private void jremarktextfield4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jremarktextfield4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jremarktextfield4KeyTyped

    private void jremarktextfield4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremarktextfield4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jremarktextfield4ActionPerformed

    private void jreceivedtextfield3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jreceivedtextfield3KeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_jreceivedtextfield3KeyTyped

    private void jreceivedtextfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreceivedtextfield3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jreceivedtextfield3ActionPerformed

    private void jcust_Idtextfield2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcust_Idtextfield2KeyTyped

        char c = evt.getKeyChar();
        if (Character.isLetter(c) &&! evt.isAltDown()) {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jcust_Idtextfield2KeyTyped

    private void jcust_Idtextfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcust_Idtextfield2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jcust_Idtextfield2ActionPerformed

    private void jbalancetextfield1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbalancetextfield1KeyTyped

        char c = evt.getKeyChar();
        if (Character.isLetter(c) &&!evt.isAltDown()) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbalancetextfield1KeyTyped

    private void jbalancetextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbalancetextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbalancetextfield1ActionPerformed

    private void jbalancetextfield1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbalancetextfield1FocusGained
        //JOptionPane.showMessageDialog(null,"hhuhuyu");
        setbalance();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbalancetextfield1FocusGained

    private void jreceivedtextfield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jreceivedtextfield3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jreceivedtextfield3FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            this.setVisible(false);
            new search_cust().setVisible(true);
        }
        catch(Exception e){}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        
        String id1=jcust_Idtextfield2.getText().trim();
        String out1= joutTextField.getText();
        String estimate1=jestimatetextfield3.getText();
        String received1=jreceivedtextfield3.getText();
        String balance1=jbalancetextfield1.getText();

          //  System.out.println(""+id1+" "+out1+" "+estimate1+" "+received1+" "+balance1);
        
            try
            {
                //this.setVisible(false);
                new recet(id1,out1).setVisible(true);
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}
                // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        {
            try
            {
                this.setVisible(false);
                new page_one().setVisible(true);
            }
            catch(Exception e){}        // TODO add your handling code here:
        
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2KeyPressed

    private void jsubmitButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsubmitButton1KeyPressed
      
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        {
        String id=jcust_Idtextfield2.getText().trim();
        String out= joutTextField.getText();
        String estimate=jestimatetextfield3.getText();
        String received=jreceivedtextfield3.getText();
        String balance=jbalancetextfield1.getText();
        String remark =jremarktextfield4.getText();
       // JOptionPane.showMessageDialog(null,"+++"+id);
        int cust_ID=0;
        try{
            
        
        cust_ID=Integer.parseInt(id);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"Exception XXXXXX");}
     //      String sql1="update customer set Estimate="+estimate+",Received="+received+",Balance="+balance+",Remark="+remark+"where cust_Id="+id;
       String sql1="update customer SET Out_Date='"+out+"',Estimate='"+estimate+"',Received='"+received+"',Balance='"+balance+"',Remark='"+remark+"' where cust_Id="+cust_ID+"";

        JOptionPane.showMessageDialog(null,sql1);
        try {
          

            //ResultSet rs;
            st.executeUpdate(sql1);
            
            JOptionPane.showMessageDialog(null,"payment completed");

        } 
        catch (Exception e) {
                      //JOptionPane.showMessageDialog(null,"#############");
            JOptionPane.showMessageDialog(null,e);

        }

        }  // TODO add your handling code here:
    }//GEN-LAST:event_jsubmitButton1KeyPressed
        public void setbalance()
        {
        //JOptionPane.showMessageDialog(null,"hhuhuyu");
        int v1=Integer.parseInt(jestimatetextfield3.getText().trim());
        int v2=Integer.parseInt(jreceivedtextfield3.getText().trim());
        String v=""+(v1-v2);
        //JOptionPane.showMessageDialog(null,"hh:"+v);
        jbalancetextfield1.setText(v);

        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details_esti_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details_esti_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details_esti_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details_esti_cust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details_esti_cust().setVisible(true);
            }
        });
    }

Statement st=null;
Connection conn=null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jbalancetextfield1;
    private javax.swing.JTextField jcust_Idtextfield2;
    private javax.swing.JLabel jdeviceLabel10;
    private javax.swing.JLabel jdeviceLabel11;
    private javax.swing.JLabel jdeviceLabel12;
    private javax.swing.JLabel jdeviceLabel8;
    private javax.swing.JLabel jdeviceLabel9;
    private javax.swing.JTextField jestimatetextfield3;
    private javax.swing.JLabel joutLabel6;
    private javax.swing.JFormattedTextField joutTextField;
    private javax.swing.JTextField jreceivedtextfield3;
    private javax.swing.JTextField jremarktextfield4;
    private javax.swing.JButton jsubmitButton1;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
