/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo2;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author Happy
 */
public class page_one extends javax.swing.JFrame {

    /**
     * Creates new form page_one
     */
    public page_one() {
        
        this.setUndecorated(true);
        this.setVisible(true);
        
        initComponents();
        
       Toolkit tk = Toolkit.getDefaultToolkit();
        
        int xsize = (int)tk.getScreenSize().getWidth();
       int ysize = (int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jnewentry_delar_Button1 = new javax.swing.JButton();
        jpending_delar_Button1 = new javax.swing.JButton();
        jdetails_esti_cust_Button1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jnewentry_cust_Button2 = new javax.swing.JButton();
        jpending_cust_Button2 = new javax.swing.JButton();
        jdetails_esti_delar_Button2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jpending_Amount_delar_Button1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jpending_Amount_cust_Button2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(79, 195, 247));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Stocks");

        jnewentry_delar_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jnewentry_delar_Button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\UI_2-16.png")); // NOI18N
        jnewentry_delar_Button1.setText("  New Entry_Delar");
        jnewentry_delar_Button1.setAutoscrolls(true);
        jnewentry_delar_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewentry_delar_Button1ActionPerformed(evt);
            }
        });
        jnewentry_delar_Button1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jnewentry_delar_Button1KeyPressed(evt);
            }
        });

        jpending_delar_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpending_delar_Button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\Laptop-16.png")); // NOI18N
        jpending_delar_Button1.setText(" Pending items_repaire");
        jpending_delar_Button1.setAutoscrolls(true);
        jpending_delar_Button1.setDoubleBuffered(true);
        jpending_delar_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpending_delar_Button1ActionPerformed(evt);
            }
        });
        jpending_delar_Button1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpending_delar_Button1KeyPressed(evt);
            }
        });

        jdetails_esti_cust_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jdetails_esti_cust_Button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\calculator_budget_estimation_maths-16.png")); // NOI18N
        jdetails_esti_cust_Button1.setText(" Details And Estimation");
        jdetails_esti_cust_Button1.setAutoscrolls(true);
        jdetails_esti_cust_Button1.setFocusTraversalPolicyProvider(true);
        jdetails_esti_cust_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdetails_esti_cust_Button1ActionPerformed(evt);
            }
        });
        jdetails_esti_cust_Button1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdetails_esti_cust_Button1KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("For Customer");

        jnewentry_cust_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jnewentry_cust_Button2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\UI_2-16.png")); // NOI18N
        jnewentry_cust_Button2.setText("  New Entry_Customer");
        jnewentry_cust_Button2.setAutoscrolls(true);
        jnewentry_cust_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewentry_cust_Button2ActionPerformed(evt);
            }
        });
        jnewentry_cust_Button2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jnewentry_cust_Button2KeyPressed(evt);
            }
        });

        jpending_cust_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpending_cust_Button2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\Laptop-16.png")); // NOI18N
        jpending_cust_Button2.setText(" Pending items_repaire");
        jpending_cust_Button2.setAutoscrolls(true);
        jpending_cust_Button2.setDoubleBuffered(true);
        jpending_cust_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpending_cust_Button2ActionPerformed(evt);
            }
        });
        jpending_cust_Button2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpending_cust_Button2KeyPressed(evt);
            }
        });

        jdetails_esti_delar_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jdetails_esti_delar_Button2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\calculator_budget_estimation_maths-16.png")); // NOI18N
        jdetails_esti_delar_Button2.setText(" Details And Estimation");
        jdetails_esti_delar_Button2.setAutoscrolls(true);
        jdetails_esti_delar_Button2.setFocusTraversalPolicyProvider(true);
        jdetails_esti_delar_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdetails_esti_delar_Button2ActionPerformed(evt);
            }
        });
        jdetails_esti_delar_Button2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdetails_esti_delar_Button2KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("For Delar");

        jpending_Amount_delar_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpending_Amount_delar_Button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\Amount-16.png")); // NOI18N
        jpending_Amount_delar_Button1.setText(" Pending _Amount_Delar");
        jpending_Amount_delar_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpending_Amount_delar_Button1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Pending Amount");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\database_4_32.png")); // NOI18N
        jButton2.setText(" Stocks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jpending_Amount_cust_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpending_Amount_cust_Button2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\Amount-16.png")); // NOI18N
        jpending_Amount_cust_Button2.setText(" Pending _Amount_Customer");
        jpending_Amount_cust_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpending_Amount_cust_Button2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText(" EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText(" ID_and_Name_customer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText(" ID_and_Name_Delar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("ID And Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpending_Amount_cust_Button2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jnewentry_delar_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpending_cust_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpending_Amount_delar_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpending_delar_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jdetails_esti_cust_Button1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdetails_esti_delar_Button2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(jnewentry_cust_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(688, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnewentry_delar_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpending_delar_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdetails_esti_delar_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdetails_esti_cust_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpending_cust_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(106, 106, 106)))
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpending_Amount_cust_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpending_Amount_delar_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jnewentry_cust_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(724, Short.MAX_VALUE)))
        );

        jpending_Amount_cust_Button2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnewentry_delar_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewentry_delar_Button1ActionPerformed
        try
        {
        this.setVisible(false);
        new main2().setVisible(true);
        }
        catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewentry_delar_Button1ActionPerformed

    private void jnewentry_delar_Button1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnewentry_delar_Button1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try{
            this.setVisible(false);
            new main2().setVisible(true);
            }
            catch(Exception e){}
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jnewentry_delar_Button1KeyPressed

    private void jpending_delar_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpending_delar_Button1ActionPerformed

        try{
            this.setVisible(false);
            new pending_item_repaire_delar().setVisible(true);
            }
            catch(Exception e){}
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jpending_delar_Button1ActionPerformed

    private void jdetails_esti_cust_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdetails_esti_cust_Button1ActionPerformed
    
        try{
        this.setVisible(false);
        new search_cust().setVisible(true);
        }
        catch(Exception e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jdetails_esti_cust_Button1ActionPerformed

    private void jnewentry_cust_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewentry_cust_Button2ActionPerformed
      
        try
        {
        this.setVisible(false);
        new main1().setVisible(true);
        }
        catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewentry_cust_Button2ActionPerformed

    private void jnewentry_cust_Button2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnewentry_cust_Button2KeyPressed
    
            if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try{
            this.setVisible(false);
            new main1().setVisible(true);
            }
            catch(Exception e){}
        }

    
    // TODO add your handling code here:
    }//GEN-LAST:event_jnewentry_cust_Button2KeyPressed

    private void jpending_cust_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpending_cust_Button2ActionPerformed
       
        try{
        this.setVisible(false);
        new pending_item_repaire_cust().setVisible(true);
        }
        catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jpending_cust_Button2ActionPerformed

    private void jdetails_esti_delar_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdetails_esti_delar_Button2ActionPerformed

            try{
            this.setVisible(false);
            new search_delar().setVisible(true);
            }
            catch(Exception e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jdetails_esti_delar_Button2ActionPerformed

    private void jpending_Amount_delar_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpending_Amount_delar_Button1ActionPerformed

            try{
            this.setVisible(false);
            new pendingAmount_delar().setVisible(true);
            }
            catch(Exception e){}
            // TODO add your handling code here:
    }//GEN-LAST:event_jpending_Amount_delar_Button1ActionPerformed

    private void jpending_Amount_cust_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpending_Amount_cust_Button2ActionPerformed
        
            try{
            this.setVisible(false);
            new pendingAmount_cust().setVisible(true);
            }
            catch(Exception e){}
// TODO add your handling code here:
    }//GEN-LAST:event_jpending_Amount_cust_Button2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            try{
            this.setVisible(false);
            new stock_item().setVisible(true);
            }
            catch(Exception e){}
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
           System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jpending_cust_Button2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpending_cust_Button2KeyPressed

    if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     {
        
        try{
        this.setVisible(false);
        new pending_item_repaire_cust().setVisible(true);
        }
        catch(Exception e){}

     }
        // TODO add your handling code here:
    }//GEN-LAST:event_jpending_cust_Button2KeyPressed

    private void jdetails_esti_cust_Button1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdetails_esti_cust_Button1KeyPressed
 
     if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     {
     try{
        this.setVisible(false);
        new search_cust().setVisible(true);
        }
        catch(Exception e){}
     
     }
// TODO add your handling code here:
    }//GEN-LAST:event_jdetails_esti_cust_Button1KeyPressed

    private void jpending_delar_Button1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpending_delar_Button1KeyPressed

    if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     {
      try{
            this.setVisible(false);
            new pending_item_repaire_delar().setVisible(true);
            }
            catch(Exception e){}
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_jpending_delar_Button1KeyPressed

    private void jdetails_esti_delar_Button2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdetails_esti_delar_Button2KeyPressed
 
      if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     {
        try{
        this.setVisible(false);
        new search_delar().setVisible(true);
        }
        catch(Exception e){}
        
     }
// TODO add your handling code here:
    }//GEN-LAST:event_jdetails_esti_delar_Button2KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
            this.setVisible(false);
            new Id_name().setVisible(true);
            }
            catch(Exception e){}
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            this.setVisible(false);
            new Id_name_delar().setVisible(true);
            }
            catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     {
    try{
            this.setVisible(false);
            new Id_name().setVisible(true);
            }
            catch(Exception e){}
     }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
     {
    try{
            this.setVisible(false);
            new Id_name_delar().setVisible(true);
            }
            catch(Exception e){}
     }
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page_one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page_one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page_one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page_one.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page_one().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jdetails_esti_cust_Button1;
    private javax.swing.JButton jdetails_esti_delar_Button2;
    private javax.swing.JButton jnewentry_cust_Button2;
    private javax.swing.JButton jnewentry_delar_Button1;
    private javax.swing.JButton jpending_Amount_cust_Button2;
    private javax.swing.JButton jpending_Amount_delar_Button1;
    private javax.swing.JButton jpending_cust_Button2;
    private javax.swing.JButton jpending_delar_Button1;
    // End of variables declaration//GEN-END:variables
}
