/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo2;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Happy
 */
public class stock_item extends javax.swing.JFrame {

    /**
     * Creates new form stock_item
     */
        public stock_item() {
            this.setUndecorated(true);
            this.setVisible(true);
       
            initComponents();
            Toolkit tk = Toolkit.getDefaultToolkit();
        
            int xsize = (int)tk.getScreenSize().getWidth();
            int ysize = (int)tk.getScreenSize().getHeight();
            this.setSize(xsize,ysize);
            try 
            {
                    Class.forName("com.mysql.jdbc.Driver");
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/list_info?zeroDateTimeBehavior=convertToNull","root","");     
                    st = conn.createStatement();
                   JOptionPane.showMessageDialog(null,"Connected");
                   // MySQL database connection
             } 
             catch (Exception e) 
             {
                    JOptionPane.showMessageDialog(null,"Not Connected");
             }
        
              String sql3="select * from stock";
              ResultSet rs=null;
              try{
                    rs=st.executeQuery(sql3);
                    tran1 = null;
                    while(rs.next())
                    {
                     tran1=rs.getString("transistor");
                     diode1=rs.getString("diode");
                     resistor1=rs.getString("resistor");
                     ics1=rs.getString("ics");
                     capacitor1 = rs.getString("capacitor");
                     connector1 = rs.getString("connector");
                     regulator1 = rs.getString("regulator");
                     rectifiers1 = rs.getString("rectifiers");
                     cystal1 = rs.getString("cystal");;
                    glass_fuels1 = rs.getString("glass_fuels");;
                     octo_couplors1 = rs.getString("octo_couplors");;

                    }
                    jLabel12.setText(tran1);
                    jLabel13.setText(diode1);
                    jLabel14.setText(resistor1);
                    jLabel15.setText(ics1);
                    jLabel18.setText(capacitor1);
                    jLabel16.setText(connector1);
                    jLabel17.setText(regulator1);
                    jLabel19.setText(rectifiers1);
                    jLabel20.setText(cystal1);
                    jLabel21.setText(glass_fuels1);
                    jLabel22.setText(octo_couplors1);
                    
                    
                 //tr=Integer.parseInt(tran);
              }
           catch(SQLException e){}
        
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCrystal_Button1 = new javax.swing.JButton();
        jConnector_Button2 = new javax.swing.JButton();
        jDiode_Button1 = new javax.swing.JButton();
        jResistor_Button2 = new javax.swing.JButton();
        Ics_Button2 = new javax.swing.JButton();
        jCapacitor_Button2 = new javax.swing.JButton();
        jRectifiers_Button2 = new javax.swing.JButton();
        jRegulator_Button2 = new javax.swing.JButton();
        jtransistor_Button2 = new javax.swing.JButton();
        jOcto_Couplors_Button1 = new javax.swing.JButton();
        jGlassFuels_Button2 = new javax.swing.JButton();
        jtransistor_Button1 = new javax.swing.JButton();
        jDiode_Button2 = new javax.swing.JButton();
        jResistor_Button1 = new javax.swing.JButton();
        jCapacitor_Button1 = new javax.swing.JButton();
        jConnector_Button1 = new javax.swing.JButton();
        jRegulator_Button1 = new javax.swing.JButton();
        jRectifiers_Button1 = new javax.swing.JButton();
        jIcs_Button1 = new javax.swing.JButton();
        jCrystal_Button2 = new javax.swing.JButton();
        jGlassFuels_Button1 = new javax.swing.JButton();
        jOcto_Couplors_Button2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(79, 195, 247));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText(" Transistor:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText(" Diode:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText(" Resistor:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("  Ics:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText(" Capacitor:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("       Connector:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("  Regulator:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText(" Rectifiers:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText(" Cystal:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText(" Glass Fuels:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText(" Octo_Couplors:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText(" ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText(" ");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText(" ");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText(" ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText(" ");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText(" ");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText(" ");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText(" ");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText(" ");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText(" ");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText(" ");

        jCrystal_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCrystal_Button1.setText("+");
        jCrystal_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrystal_Button1ActionPerformed(evt);
            }
        });

        jConnector_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jConnector_Button2.setText("-");
        jConnector_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnector_Button2ActionPerformed(evt);
            }
        });

        jDiode_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jDiode_Button1.setText("+");
        jDiode_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiode_Button1ActionPerformed(evt);
            }
        });

        jResistor_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jResistor_Button2.setText("-");
        jResistor_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResistor_Button2ActionPerformed(evt);
            }
        });

        Ics_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Ics_Button2.setText("-");
        Ics_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ics_Button2ActionPerformed(evt);
            }
        });

        jCapacitor_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCapacitor_Button2.setText("-");
        jCapacitor_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacitor_Button2ActionPerformed(evt);
            }
        });

        jRectifiers_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRectifiers_Button2.setText("-");
        jRectifiers_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRectifiers_Button2ActionPerformed(evt);
            }
        });

        jRegulator_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRegulator_Button2.setText("-");
        jRegulator_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegulator_Button2ActionPerformed(evt);
            }
        });

        jtransistor_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtransistor_Button2.setText("-");
        jtransistor_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtransistor_Button2ActionPerformed(evt);
            }
        });

        jOcto_Couplors_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jOcto_Couplors_Button1.setText("+");
        jOcto_Couplors_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOcto_Couplors_Button1ActionPerformed(evt);
            }
        });

        jGlassFuels_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jGlassFuels_Button2.setText("-");
        jGlassFuels_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGlassFuels_Button2ActionPerformed(evt);
            }
        });

        jtransistor_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtransistor_Button1.setText(" +");
        jtransistor_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtransistor_Button1ActionPerformed(evt);
            }
        });

        jDiode_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jDiode_Button2.setText("-");
        jDiode_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiode_Button2ActionPerformed(evt);
            }
        });

        jResistor_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jResistor_Button1.setText("+");
        jResistor_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResistor_Button1ActionPerformed(evt);
            }
        });

        jCapacitor_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCapacitor_Button1.setText("+");
        jCapacitor_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCapacitor_Button1ActionPerformed(evt);
            }
        });

        jConnector_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jConnector_Button1.setText("+");
        jConnector_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnector_Button1ActionPerformed(evt);
            }
        });

        jRegulator_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRegulator_Button1.setText("+");
        jRegulator_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegulator_Button1ActionPerformed(evt);
            }
        });

        jRectifiers_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRectifiers_Button1.setText("+");
        jRectifiers_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRectifiers_Button1ActionPerformed(evt);
            }
        });

        jIcs_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jIcs_Button1.setText("+");
        jIcs_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIcs_Button1ActionPerformed(evt);
            }
        });

        jCrystal_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCrystal_Button2.setText("-");
        jCrystal_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrystal_Button2ActionPerformed(evt);
            }
        });

        jGlassFuels_Button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jGlassFuels_Button1.setText("+");
        jGlassFuels_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGlassFuels_Button1ActionPerformed(evt);
            }
        });

        jOcto_Couplors_Button2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jOcto_Couplors_Button2.setText("-");
        jOcto_Couplors_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOcto_Couplors_Button2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Happy\\Desktop\\demo2\\src\\demo2\\restart-1.png")); // NOI18N
        jButton2.setText("Back");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRectifiers_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegulator_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConnector_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCapacitor_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIcs_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jResistor_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiode_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtransistor_Button1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtransistor_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiode_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jResistor_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ics_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCapacitor_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConnector_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegulator_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRectifiers_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCrystal_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jGlassFuels_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jOcto_Couplors_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jGlassFuels_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jOcto_Couplors_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jCrystal_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDiode_Button1)
                            .addComponent(jDiode_Button2)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCrystal_Button1)
                            .addComponent(jCrystal_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtransistor_Button1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtransistor_Button2))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGlassFuels_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGlassFuels_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOcto_Couplors_Button1)
                            .addComponent(jOcto_Couplors_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jResistor_Button2)
                            .addComponent(jResistor_Button1)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ics_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jIcs_Button1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCapacitor_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCapacitor_Button1)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jConnector_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jConnector_Button1)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRegulator_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRegulator_Button1)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRectifiers_Button1)
                    .addComponent(jRectifiers_Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDiode_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiode_Button1ActionPerformed
        


           String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("diode");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET diode="+result+" where diode="+temp+"";
                st.executeUpdate(sql4);
                jLabel13.setText(""+result);
                }
                catch(SQLException e){}
// TODO add your handling code here:
    }//GEN-LAST:event_jDiode_Button1ActionPerformed

    private void jResistor_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResistor_Button2ActionPerformed

        String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
            
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("resistor");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrese:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET resistor="+result+" where resistor="+temp+"";
                st.executeUpdate(sql4);
                jLabel14.setText(""+result);
                }
                 catch(Exception e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jResistor_Button2ActionPerformed

    private void jRegulator_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegulator_Button2ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
            
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("regulator");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrese:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET regulator="+result+" where regulator="+temp+"";
                st.executeUpdate(sql4);
                jLabel17.setText(""+result);
                }
                 catch(Exception e){}


        // TODO add your handling code here:
    }//GEN-LAST:event_jRegulator_Button2ActionPerformed

    private void jtransistor_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtransistor_Button2ActionPerformed
 
                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
            
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("transistor");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrese:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET transistor="+result+" where transistor="+temp+"";
                st.executeUpdate(sql4);
                jLabel12.setText(""+result);

            //      this.setVisible(false);
              //  new stock_value_change(tran_ng).setVisible(true);
                 //tr=Integer.parseInt(tran);
                   
            }
           catch(SQLException e){}
            // TODO add your handling code here:
    }//GEN-LAST:event_jtransistor_Button2ActionPerformed

    private void jtransistor_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtransistor_Button1ActionPerformed

           String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("transistor");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET transistor="+result+" where transistor="+temp+"";
                st.executeUpdate(sql4);
                jLabel12.setText(""+result);
                }
                catch(SQLException e){}
            // TODO add your handling code here:
    }//GEN-LAST:event_jtransistor_Button1ActionPerformed

    private void jDiode_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiode_Button2ActionPerformed

            String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("diode");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrease:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET diode="+result+" where diode="+temp+"";
                st.executeUpdate(sql4);
                jLabel13.setText(""+result);
                }
                catch(SQLException e){}



        // TODO add your handling code here:
    }//GEN-LAST:event_jDiode_Button2ActionPerformed

    private void jCapacitor_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacitor_Button2ActionPerformed
                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
            
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("capacitor");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrese:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET capacitor="+result+" where capacitor="+temp+"";
                st.executeUpdate(sql4);
                jLabel18.setText(""+result);
                }
                catch(SQLException e){}
                // TODO add your handling code here:
    }//GEN-LAST:event_jCapacitor_Button2ActionPerformed

    private void jResistor_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResistor_Button1ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("resistor");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET resistor="+result+" where resistor="+temp+"";
                st.executeUpdate(sql4);
                jLabel14.setText(""+result);
                }
                catch(SQLException e){}


        // TODO add your handling code here:
    }//GEN-LAST:event_jResistor_Button1ActionPerformed

    private void jOcto_Couplors_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOcto_Couplors_Button1ActionPerformed

            String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("octo_couplors");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET octo_couplors="+result+" where octo_couplors="+temp+"";
                st.executeUpdate(sql4);
                jLabel22.setText(""+result);
                }
                catch(SQLException e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jOcto_Couplors_Button1ActionPerformed

    private void jOcto_Couplors_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOcto_Couplors_Button2ActionPerformed
                
                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("octo_couplors");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrease:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET octo_couplors="+result+" where octo_couplors="+temp+"";
                st.executeUpdate(sql4);
                jLabel22.setText(""+result);
                }
                catch(SQLException e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jOcto_Couplors_Button2ActionPerformed

    private void jIcs_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIcs_Button1ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("ics");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET ics="+result+" where ics="+temp+"";
                st.executeUpdate(sql4);
                jLabel15.setText(""+result);
                }
                catch(SQLException e){}


        // TODO add your handling code here:
    }//GEN-LAST:event_jIcs_Button1ActionPerformed

    private void Ics_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ics_Button2ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("ics");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrease:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET ics="+result+" where ics="+temp+"";
                st.executeUpdate(sql4);
                jLabel15.setText(""+result);
                }
                catch(SQLException e){}


    }//GEN-LAST:event_Ics_Button2ActionPerformed

    private void jCapacitor_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCapacitor_Button1ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("capacitor");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET capacitor="+result+" where capacitor="+temp+"";
                st.executeUpdate(sql4);
                jLabel18.setText(""+result);
                }
                catch(SQLException e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jCapacitor_Button1ActionPerformed

    private void jConnector_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnector_Button1ActionPerformed


            String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("connector");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET connector="+result+" where connector="+temp+"";
                st.executeUpdate(sql4);
                jLabel16.setText(""+result);
                }
                catch(SQLException e){}



        // TODO add your handling code here:
    }//GEN-LAST:event_jConnector_Button1ActionPerformed

    private void jConnector_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnector_Button2ActionPerformed

            String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("connector");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrease:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET connector="+result+" where connector="+temp+"";
                st.executeUpdate(sql4);
                jLabel16.setText(""+result);
                }
                catch(SQLException e){}


        // TODO add your handling code here:
    }//GEN-LAST:event_jConnector_Button2ActionPerformed

    private void jRegulator_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegulator_Button1ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("regulator");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET regulator="+result+" where regulator="+temp+"";
                st.executeUpdate(sql4);
                jLabel17.setText(""+result);
                }
                catch(SQLException e){}


        // TODO add your handling code here:
    }//GEN-LAST:event_jRegulator_Button1ActionPerformed

    private void jRectifiers_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRectifiers_Button1ActionPerformed


                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("rectifiers");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET rectifiers="+result+" where rectifiers="+temp+"";
                st.executeUpdate(sql4);
                jLabel19.setText(""+result);
                }
                catch(SQLException e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jRectifiers_Button1ActionPerformed

    private void jRectifiers_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRectifiers_Button2ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("rectifiers");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrease:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET rectifiers="+result+" where rectifiers="+temp+"";
                st.executeUpdate(sql4);
                jLabel19.setText(""+result);
                }
                catch(SQLException e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_jRectifiers_Button2ActionPerformed

    private void jCrystal_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrystal_Button1ActionPerformed

                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("cystal");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET  cystal="+result+" where cystal="+temp+"";
                st.executeUpdate(sql4);
                jLabel20.setText(""+result);
                }
                catch(SQLException e){}


        // TODO add your handling code here:
    }//GEN-LAST:event_jCrystal_Button1ActionPerformed

    private void jGlassFuels_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGlassFuels_Button1ActionPerformed

                String sql3="select * from stock";
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("glass_fuels");
                 
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int increase_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter increase:"));
                 result+=increase_factor;
                 
                String sql4="update stock SET  glass_fuels="+result+" where glass_fuels="+temp+"";
                st.executeUpdate(sql4);
                jLabel21.setText(""+result);
                }
                catch(SQLException e){}


        // TODO add your handling code here:
    }//GEN-LAST:event_jGlassFuels_Button1ActionPerformed

    private void jCrystal_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrystal_Button2ActionPerformed
        
                String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("cystal");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrease:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET cystal="+result+" where cystal="+temp+"";
                st.executeUpdate(sql4);
                jLabel20.setText(""+result);
                }
                catch(SQLException e){}
                 // TODO add your handling code here:
    }//GEN-LAST:event_jCrystal_Button2ActionPerformed

    private void jGlassFuels_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGlassFuels_Button2ActionPerformed
        

        String sql3="select * from stock";
                
                ResultSet rs=null;
                int result=0;
                
                try{
                 rs=st.executeQuery(sql3);
                 tran_ng=null;
                 
                 while(rs.next())
                 {
                     tran_ng=""+rs.getInt("glass_fuels");
                    
                 }
                 result=Integer.parseInt(tran_ng);
                 int temp=result;
                 int decrease_factor=Integer.parseInt(JOptionPane.showInputDialog(null, "Enter decrease:"));
                 result-=decrease_factor;
                 
                String sql4="update stock SET glass_fuels="+result+" where glass_fuels="+temp+"";
                st.executeUpdate(sql4);
                jLabel21.setText(""+result);
                }
                catch(SQLException e){}

    // TODO add your handling code here:
    }//GEN-LAST:event_jGlassFuels_Button2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            this.setVisible(false);
            new page_one().setVisible(true);
        }
        catch(Exception e){}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
        try
        {
            this.setVisible(false);
            new page_one().setVisible(true);
        }
        catch(Exception e){}

        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new stock_item().setVisible(true);
        });
    }
Statement st;
Connection conn;


String tran_ng=null;
String tran_po=null;
String tran1=null;
String diode1=null;
String resistor1=null;
String ics1=null; 

String capacitor1;
String connector1;
String regulator1;
String rectifiers1;
String  cystal1;
String  glass_fuels1;
String  octo_couplors1;

ResultSet rs=null;

int tr=0;
int per=0;
int gv=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ics_Button2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCapacitor_Button1;
    private javax.swing.JButton jCapacitor_Button2;
    private javax.swing.JButton jConnector_Button1;
    private javax.swing.JButton jConnector_Button2;
    private javax.swing.JButton jCrystal_Button1;
    private javax.swing.JButton jCrystal_Button2;
    private javax.swing.JButton jDiode_Button1;
    private javax.swing.JButton jDiode_Button2;
    private javax.swing.JButton jGlassFuels_Button1;
    private javax.swing.JButton jGlassFuels_Button2;
    private javax.swing.JButton jIcs_Button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jOcto_Couplors_Button1;
    private javax.swing.JButton jOcto_Couplors_Button2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRectifiers_Button1;
    private javax.swing.JButton jRectifiers_Button2;
    private javax.swing.JButton jRegulator_Button1;
    private javax.swing.JButton jRegulator_Button2;
    private javax.swing.JButton jResistor_Button1;
    private javax.swing.JButton jResistor_Button2;
    private javax.swing.JButton jtransistor_Button1;
    private javax.swing.JButton jtransistor_Button2;
    // End of variables declaration//GEN-END:variables
}
